name: Deploy to GitHub Pages
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install and build
        working-directory: ./astro3
        run: |
          npm ci
          npm run deploy
      - name: Create .nojekyll
        run: touch docs/.nojekyll

  deploy:
    needs: build
    uses: actions/deploy-pages@v4